name: ClaudeHub
options:
  bundleIdPrefix: com.claudehub
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm.git
    from: 1.2.0
  ClaudeHubCore:
    path: Packages/ClaudeHubCore
  ClaudeHubTerminal:
    path: Packages/ClaudeHubTerminal

targets:
  ClaudeHub:
    type: application
    platform: macOS
    sources:
      - ClaudeHub
    dependencies:
      - package: ClaudeHubCore
      - package: ClaudeHubTerminal
      - package: SwiftTerm
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.claudehub.app
        PRODUCT_NAME: ClaudeHub
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_CFBundleDisplayName: ClaudeHub
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.developer-tools"
        SWIFT_VERSION: "5.10"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_ENTITLEMENTS: ClaudeHub/ClaudeHub.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_IDENTITY: "-"
    entitlements:
      path: ClaudeHub/ClaudeHub.entitlements
      properties:
        com.apple.security.app-sandbox: false
