name: ClaudeHubMobile
options:
  minimumXcodeGenVersion: 2.38.0
packages:
  ClaudeHubRemote:
    path: ../../Packages/ClaudeHubRemote
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm.git
    from: 1.11.2
targets:
  ClaudeHubMobile:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: App
      - path: Models
      - path: Services
      - path: Views
    dependencies:
      - package: ClaudeHubRemote
      - package: SwiftTerm
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: ClaudeHub Mobile
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSupportsIndirectInputEvents: true
        NSLocalNetworkUsageDescription: ClaudeHub Mobile discovers and connects to your paired ClaudeHub relay.
        NSCameraUsageDescription: ClaudeHub Mobile scans pairing QR codes from your Mac.
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mariomoschetta.ClaudeHubMobile
        PRODUCT_NAME: ClaudeHubMobile
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        SWIFT_VERSION: 5.10
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
